version: '3.8'

services:
  codepit:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev