import { CodeLanguage } from '../types';

export const LANGUAGE_OPTIONS: { value: CodeLanguage; label: string }[] = [
  { value: 'kql', label: 'KQL (Kusto Query Language)' },
  { value: 'sql', label: 'SQL' },
  { value: 'python', label: 'Python' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'rust', label: 'Rust' },
  { value: 'cpp', label: 'C++' },
  { value: 'c', label: 'C' },
  { value: 'java', label: 'Java' },
  { value: 'go', label: 'Go' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'csharp', label: 'C#' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'yaml', label: 'YAML' },
  { value: 'json', label: 'JSON' },
  { value: 'xml', label: 'XML' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'shell', label: 'Shell Script' },
];

export const LANGUAGE_CONTEXTS: Record<CodeLanguage, string> = {
  kql: 'Kusto Query Language (KQL) for log analytics',
  sql: 'SQL database query',
  python: 'Python programming language',
  javascript: 'JavaScript programming language',
  typescript: 'TypeScript programming language',
  rust: 'Rust programming language',
  cpp: 'C++ programming language',
  c: 'C programming language',
  java: 'Java programming language',
  go: 'Go programming language',
  ruby: 'Ruby programming language',
  php: 'PHP programming language',
  csharp: 'C# programming language',
  html: 'HTML markup',
  css: 'CSS styling',
  yaml: 'YAML configuration',
  json: 'JSON data format',
  xml: 'XML markup',
  markdown: 'Markdown documentation',
  shell: 'Shell scripting',
};

export const MONACO_LANGUAGE_MAP: Record<CodeLanguage, string> = {
  kql: 'sql',
  sql: 'sql',
  python: 'python',
  javascript: 'javascript',
  typescript: 'typescript',
  rust: 'rust',
  cpp: 'cpp',
  c: 'cpp',
  java: 'java',
  go: 'go',
  ruby: 'ruby',
  php: 'php',
  csharp: 'csharp',
  html: 'html',
  css: 'css',
  yaml: 'yaml',
  json: 'json',
  xml: 'xml',
  markdown: 'markdown',
  shell: 'shell',
};